package com.cozynote.app;

public enum AppCommand {
    NEW_NOTE,
    CLEAR_NOTE,
    SAVE_NOTE,
    UNDO,
    REDO,
    TOGGLE_UNDERLINE,
    TOGGLE_STRIKETHROUGH,
    TOGGLE_SUBSCRIPT,
    TOGGLE_SUPERSCRIPT,
    INSERT_NUMBERED_LIST,
    INDENT,
    OUTDENT,
    TOGGLE_CHECKBOX_LINES,
    INSERT_DIVIDER,
    TOGGLE_LEFT_SIDEBAR,
    TOGGLE_RIGHT_PANEL,
    OPEN_SETTINGS,
    EXPORT_BACKUP,
    IMPORT_BACKUP,
    EXIT
}
